### ISSUE TITLE
Integration not getting loaded after upgrading to 2024.10.1

### ISSUE THREAD

**Issue by kaizersoje** [dckiller51/bodymiscale#253]
The integration is not loading after upgrading to 2024.10.1

This is the error in the logs
```
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 18:28:09 (1 occurrences)
Last logged: 18:28:09

Setup failed for custom integration 'bodymiscale': Unable to import component: cannot import name 'TTLCache' from 'cachetools' (/usr/local/lib/python3.12/site-packages/cachetools/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bodymiscale/__init__.py", line 11, in <module>
    from cachetools import TTLCache
ImportError: cannot import name 'TTLCache' from 'cachetools' (/usr/local/lib/python3.12/site-packages/cachetools/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bodymiscale/__init__.py", line 11, in <module>
    from cachetools import TTLCache
ImportError: cannot import name 'TTLCache' from 'cachetools' (/usr/local/lib/python3.12/site-packages/cachetools/__init__.py)
```

**Comment by jonathan-schmieg** [comment]
@kaizersoje I'm sorry to not be able to help you - but I wanted to let you know that I do not have the same issue with 2024.10.1
maybe deleting and reinstalling the integration might help?

**Comment by dckiller51** [comment]
@kaizersoje @jonathan-schmieg 

Is the problem resolved?

**Comment by jonathan-schmieg** [comment]
@dckiller51 I never experienced the problem, I only was trying to help.

From my perspective the integration works great and I'd like to use this opportunity to say thanks.
I lost more than 10kg now and having graphs in home assistant was a huge help to keep me motivated.
THANK YOU!

**Comment by dckiller51** [comment]
@jonathan-schmieg  Thank you for your message. It makes me happy. Have a nice day.
