### ISSUE TITLE
Integration is crashing after update to 3.1.2

### ISSUE THREAD

**Issue by mibcat** [dckiller51/bodymiscale#204]
Unfortunately, the integration is no longer available after the update to 3.1.2.

### HA version
Home Assistant 2023.7.1
Frontend 20230705.1 - latest
### HACS
Integrations Version: 1.33.0
Frontend Version: 20220906112053
### Error log
```bash
homeassistant    | 2023-11-01 10:14:57.175 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration bodymiscale: Unable to import component: cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
homeassistant    |     component = integration.get_component()
homeassistant    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant    |   File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
homeassistant    |     ComponentProtocol, importlib.import_module(self.pkg_path)
homeassistant    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant    |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
homeassistant    |     return _bootstrap._gcd_import(name[level:], package, level)
homeassistant    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant    |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
homeassistant    |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
homeassistant    |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
homeassistant    |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
homeassistant    |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
homeassistant    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
homeassistant    |   File "/config/custom_components/bodymiscale/__init__.py", line 45, in <module>
homeassistant    |     from .entity import BodyScaleBaseEntity
homeassistant    |   File "/config/custom_components/bodymiscale/entity.py", line 4, in <module>
homeassistant    |     from homeassistant.helpers.device_registry import DeviceEntryType, DeviceInfo
homeassistant    | ImportError: cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)
```

Can you please have a look on that issue - thanks !

Best regrads,
Michael.

**Comment by dckiller51** [comment]
@mibcat 

[here answer](https://github.com/dckiller51/bodymiscale/issues/193#issuecomment-1764815765)

**Comment by mibcat** [comment]
Ok - thanks for the feedback.

Obviously the update integration doesn't seem to work properly (shows a wrong old version).
After updating HA everything is working as expected - Thanks again.
